trigger: none
pool: Ashu-pool
stages:
- stage: Terraform_Install
  jobs:
  - job: ToolInstall_and_INIT
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'

- stage: INITIALIZATION    
  dependsOn: Terraform_Install
  jobs:
  - job: Terraform_initialization
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Devlop'
        backendServiceArm: '20janSVC'
        backendAzureRmStorageAccountName: 'storagedevnewal'
        backendAzureRmContainerName: 'devcontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Devlop'
        environmentServiceNameAzureRM: '20janSVC'


- stage: Manual_Approval
  dependsOn: INITIALIZATION 
  pool: server
  jobs: 
  - job: Validation
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'ashutosh.pal26@outlook.com'
        approvers: 'ashutosh.pal26@outlook.com'

- stage: Deployment
  dependsOn: Manual_Approval
  jobs:
  - job: Terraform_Apply
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Devlop'
        backendServiceArm: '20janSVC'
        backendAzureRmStorageAccountName: 'storagedevnewal'
        backendAzureRmContainerName: 'devcontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/Devlop/'
        environmentServiceNameAzureRM: '20janSVC'
    